sudo: required

language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs. NOTE: you can use a bash script ( e.g. ./ci_script.sh )
install: ./travis_install_script.sh
script: cmake -G"Unix Makefiles"